language: python
sudo: required  # for gdb installation
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "nightly"
  - "pypy"

before_install:
  - sudo apt-get install gdb

install:
  - 'pip install -r dev_requirements.txt'

script:
  - make test

cache:
    directories:
        # avoid using pyPI's bandwidth when pip packages are already cached
        - $HOME/.cache/pip
